name: Build and Push Docker Image (Simple)

on:
  push:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate version
      id: version
      run: |
        # Get the number of commits since the last tag, or use current timestamp
        if git describe --tags --abbrev=0 2>/dev/null; then
          COMMIT_COUNT=$(git rev-list --count $(git describe --tags --abbrev=0)..HEAD)
          BASE_VERSION=$(git describe --tags --abbrev=0)
        else
          COMMIT_COUNT=$(git rev-list --count HEAD)
          BASE_VERSION="0.0.0"
        fi
        
        # Create incremental version
        VERSION="${BASE_VERSION}-${COMMIT_COUNT}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "commit_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
        echo "Generated version: ${VERSION}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.commit_sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image info
      run: |
        echo "Image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
        echo "Version: ${{ steps.version.outputs.version }}"
        echo "Commit SHA: ${{ steps.version.outputs.commit_sha }}"
        echo "Tags: latest, ${{ steps.version.outputs.version }}, ${{ steps.version.outputs.commit_sha }}" 